# Generated by Django 4.2.1 on 2023-06-08 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='images/')),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='serveurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nombre_processeur', models.IntegerField()),
                ('capacite_memoire', models.IntegerField()),
                ('capacite_stockage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_lancement', models.DateField()),
                ('espace_memoire_utilise', models.IntegerField()),
                ('memoire_vive_necessaire', models.IntegerField()),
                ('serveur_lancement', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administration.serveurs')),
            ],
        ),
        migrations.CreateModel(
            name='types_serveurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='usage_ressources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administration.applications')),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administration.services')),
            ],
        ),
        migrations.AddField(
            model_name='serveurs',
            name='type_serveur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administration.types_serveurs'),
        ),
        migrations.AddField(
            model_name='applications',
            name='serveur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administration.serveurs'),
        ),
        migrations.AddField(
            model_name='applications',
            name='utilisateur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administration.utilisateurs'),
        ),
    ]
