# Generated by Django 4.2.1 on 2023-06-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='email',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='prenom',
        ),
    ]
