# Generated by Django 4.2.1 on 2023-06-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_applications_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='logo',
            field=models.CharField(default='media/administration/defaut.png', max_length=100),
        ),
    ]
