# Generated by Django 4.2.1 on 2023-06-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_applications_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='logo',
            field=models.ImageField(default='media/administration/defaut.png', null=True, upload_to='media/administration/logo/'),
        ),
    ]
