# Generated by Django 4.2.1 on 2023-06-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_applications_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='logo',
            field=models.ImageField(default='logo/defaut.png', null=True, upload_to='logo/'),
        ),
    ]
